/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetbdm;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;
import oracle.jdbc.OracleStatement;
import oracle.ord.im.OrdAudio;
import oracle.ord.im.OrdImage;
import oracle.ord.im.OrdVideo;

/**
 *
 * @author al128785
 */
public class frame_ajout_film extends javax.swing.JFrame {
    String cheminPhoto="";
    String cheminBA="";
    String cheminBO="";
    List<Integer> l_acteurs;
    Image photo;
    int idR;
    /**
     * Creates new form frame_ajout_film
     */
    public frame_ajout_film() {
        
        try
        {
            initComponents();
            l_acteurs=new ArrayList(); 
            this.idR=0;
            Connection con=connexionUtils.getInstance().getConnexion();
            OracleStatement st=(OracleStatement) con.createStatement();
            OracleResultSet rs=(OracleResultSet)st.executeQuery("SELECT nom FROM PBDM_Acteur");
            while(rs.next())
            {
                this.cb_acteurs.addItem(rs.getString(1));
            }
            rs=(OracleResultSet) st.executeQuery("SELECT nom FROM PBDM_Realisateur");
            while(rs.next())
            {
                this.cb_real.addItem(rs.getString(1));
            }
        }
        catch (SQLException | ClassNotFoundException ex)
        {
            Logger.getLogger(frame_ajout_film.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    @Override
    public void paint(Graphics g)
    {
        super.paint(g);
        if(this.photo!=null)
            this.affiche();
    }
    
    private void affiche()
    {
        Graphics g = this.pan_image.getGraphics();
        g.drawImage(this.photo, 0, 0, this.pan_image.getWidth(), this.pan_image.getHeight(), this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTextField1 = new javax.swing.JTextField();
        label_frame = new javax.swing.JLabel();
        pan_principal = new javax.swing.JPanel();
        label_titre = new javax.swing.JLabel();
        field_titre = new javax.swing.JTextField();
        label_date = new javax.swing.JLabel();
        field_date = new javax.swing.JTextField();
        label_synopsis = new javax.swing.JLabel();
        pan_text = new javax.swing.JScrollPane();
        edition_synopsis = new javax.swing.JTextArea();
        pan_image = new javax.swing.JPanel();
        button_image = new javax.swing.JButton();
        label_genre = new javax.swing.JLabel();
        field_genre = new javax.swing.JTextField();
        button_ajoutA = new javax.swing.JButton();
        cb_acteurs = new javax.swing.JComboBox<>();
        cb_real = new javax.swing.JComboBox<>();
        button_ajoutR = new javax.swing.JButton();
        pan_buttons = new javax.swing.JPanel();
        button_ba = new javax.swing.JButton();
        button_bo = new javax.swing.JButton();
        button_annuler = new javax.swing.JButton();
        button_valider = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        label_frame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_frame.setText("Ajout d'un film");
        label_frame.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(label_frame, java.awt.BorderLayout.NORTH);

        label_titre.setText("Titre");

        label_date.setText("Date de sortie");

        label_synopsis.setText("Synopsis");

        edition_synopsis.setColumns(20);
        edition_synopsis.setRows(5);
        pan_text.setViewportView(edition_synopsis);

        pan_image.setMaximumSize(new java.awt.Dimension(300, 300));
        pan_image.setMinimumSize(new java.awt.Dimension(20, 20));
        pan_image.setPreferredSize(new java.awt.Dimension(100, 125));

        javax.swing.GroupLayout pan_imageLayout = new javax.swing.GroupLayout(pan_image);
        pan_image.setLayout(pan_imageLayout);
        pan_imageLayout.setHorizontalGroup(
            pan_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pan_imageLayout.setVerticalGroup(
            pan_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
        );

        button_image.setText("Image");
        button_image.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                button_imageActionPerformed(evt);
            }
        });

        label_genre.setText("Genre");

        button_ajoutA.setText("Ajouter un acteur");
        button_ajoutA.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                button_ajoutAActionPerformed(evt);
            }
        });

        button_ajoutR.setText("Ajouter un réalisateur");
        button_ajoutR.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                button_ajoutRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan_principalLayout = new javax.swing.GroupLayout(pan_principal);
        pan_principal.setLayout(pan_principalLayout);
        pan_principalLayout.setHorizontalGroup(
            pan_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_synopsis)
                    .addComponent(pan_text, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_principalLayout.createSequentialGroup()
                        .addGroup(pan_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_titre)
                            .addComponent(label_date)
                            .addComponent(label_genre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pan_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(field_titre, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(field_date)
                            .addComponent(field_genre))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pan_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pan_principalLayout.createSequentialGroup()
                        .addGroup(pan_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pan_image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_image, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56))
                    .addGroup(pan_principalLayout.createSequentialGroup()
                        .addGroup(pan_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cb_real, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_acteurs, 0, 53, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pan_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button_ajoutA)
                            .addComponent(button_ajoutR, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        pan_principalLayout.setVerticalGroup(
            pan_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan_principalLayout.createSequentialGroup()
                        .addGroup(pan_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_titre)
                            .addComponent(field_titre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pan_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_date)
                            .addComponent(field_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pan_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_genre)
                            .addComponent(field_genre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_synopsis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pan_text))
                    .addGroup(pan_principalLayout.createSequentialGroup()
                        .addComponent(pan_image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_image)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pan_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_real, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_ajoutR))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pan_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button_ajoutA)
                            .addComponent(cb_acteurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        getContentPane().add(pan_principal, java.awt.BorderLayout.CENTER);

        pan_buttons.setLayout(new java.awt.GridLayout(2, 2));

        button_ba.setText("Bande-annonce");
        button_ba.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                button_baActionPerformed(evt);
            }
        });
        pan_buttons.add(button_ba);

        button_bo.setText("Bande originale");
        button_bo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                button_boActionPerformed(evt);
            }
        });
        pan_buttons.add(button_bo);

        button_annuler.setText("Annuler");
        button_annuler.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                button_annulerActionPerformed(evt);
            }
        });
        pan_buttons.add(button_annuler);

        button_valider.setText("Valider");
        button_valider.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                button_validerActionPerformed(evt);
            }
        });
        pan_buttons.add(button_valider);

        getContentPane().add(pan_buttons, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_imageActionPerformed
                                               
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Choisir une photo");
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Images", "bmp", "jpg", "jpeg", "png");
        fileChooser.addChoosableFileFilter(filter);
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.setFileFilter(filter);
        if(fileChooser.showOpenDialog(this)==JFileChooser.APPROVE_OPTION)
        {
            //Récupération de l'image
            this.cheminPhoto = fileChooser.getSelectedFile().getAbsolutePath();
            this.photo = Toolkit.getDefaultToolkit().getImage(this.cheminPhoto);
            this.affiche();
        }
    }//GEN-LAST:event_button_imageActionPerformed

    private void button_validerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_button_validerActionPerformed
    {//GEN-HEADEREND:event_button_validerActionPerformed
        try
        {
            int index=0;
            Connection con=connexionUtils.getInstance().getConnexion();
            con.setAutoCommit(false);
            Statement s=null;
            
            s = con.createStatement();
            OracleResultSet rs=null;
            
            rs=(OracleResultSet) s.executeQuery("INSERT INTO PBDM_Film VALUES("+index+",'"+this.field_date.getText()+"','"+this.field_titre.getText()+"','"+this.edition_synopsis.getText()+"','"+this.field_genre.getText()+"',ORDSYS.ORDImage.init(),ORDSYS.ORDVideo.init(),ORDSYS.ORDAudio.init(), (SELECT REF(r) FROM PBDM_Realisateur r WHERE id="+this.idR+"))");
            index=-1;
            rs=(OracleResultSet)s.executeQuery("select id, image, bandeA, bandeO from PBDM_Film where nom='"+this.field_titre.getText()+"' for update");
            while(rs.next())
            {
                index=rs.getInt(1);
                OraclePreparedStatement or=(OraclePreparedStatement) con.prepareStatement("INSERT INTO THE(SELECT filmsR FROM PBDM_Realisateur r WHERE r.id="+this.idR+") SELECT REF(f) FROM PBDM_Film f WHERE f.id=?");
                or.setInt(1, index);
                or.execute();
                or.close();
                OrdImage imgObj= (OrdImage)rs.getORAData(2,OrdImage.getORADataFactory());
                OrdVideo vidObj= (OrdVideo)rs.getORAData(3,OrdVideo.getORADataFactory());
                OrdAudio sonObj= (OrdAudio)rs.getORAData(4,OrdAudio.getORADataFactory());
                String fich=this.cheminPhoto;
                String vid=this.cheminBA;
                String son=this.cheminBO;
                if(!(this.cheminPhoto.equals("")))
                        imgObj.loadDataFromFile(fich);
                if(!(this.cheminBA.equals("")))
                    vidObj.loadDataFromFile(vid);
                if(!(this.cheminBO.equals("")))
                    sonObj.loadDataFromFile(son);
                byte[] ctx[] = new byte [4000][1];
                imgObj.setProperties();
                if(!(this.cheminBA.equals("")))
                   vidObj.setProperties(ctx);
                if(!(this.cheminBO.equals("")))
                    sonObj.setProperties(ctx);
                OraclePreparedStatement stmt1;
                if((!this.cheminBA.equals(""))&&(!this.cheminBO.equals("")))
                {
                    stmt1=(OraclePreparedStatement)con.prepareStatement("update PBDM_Film set image=?,bandeA=?,bandeO=? where id="+index);
                    stmt1.setORAData(1,imgObj);
                    stmt1.setORAData(2,vidObj);
                    stmt1.setORAData(3,sonObj);
                }
                else if((!this.cheminBA.equals("")))
                {
                    stmt1=(OraclePreparedStatement)con.prepareStatement("update PBDM_Film set image=?,bandeA=? where id="+index);
                    stmt1.setORAData(1,imgObj);
                    stmt1.setORAData(2,vidObj);
                }
                else
                {
                    stmt1=(OraclePreparedStatement)con.prepareStatement("update PBDM_Film set image=? where id="+index);
                    stmt1.setORAData(1,imgObj);
                }
                stmt1.execute();
                stmt1.close();   
            }
            rs=(OracleResultSet)s.executeQuery("ALTER INDEX PBDM_indexF REBUILD");
            rs=(OracleResultSet)s.executeQuery("ALTER INDEX PBDM_indexSF REBUILD");
            OraclePreparedStatement st=null;
            if(!this.l_acteurs.isEmpty())
            {
                for(int i=0;i<this.l_acteurs.size();i++)
                {
                    st=(OraclePreparedStatement) con.prepareStatement("INSERT INTO PBDM_MedVidActeur VALUES((SELECT REF(a) FROM PBDM_Acteur a WHERE id=?),(SELECT REF(f) FROM PBDM_Film f WHERE id=?))");
                    st.setInt(1,this.l_acteurs.get(i));
                    st.setInt(2,index);
                    st.execute();
                    st.close();
                }
            }
            rs.close();
            s.close();
            
            con.commit();
        }
        catch (SQLException | IOException | ClassNotFoundException ex)
        {
            Logger.getLogger(frame_ajout_film.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_button_validerActionPerformed

    private void button_baActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_baActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Choisir une vidéo");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Videos", "avi", "mkv", "mp4");
        fileChooser.addChoosableFileFilter(filter);
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.setFileFilter(filter);
        if(fileChooser.showOpenDialog(this)==JFileChooser.APPROVE_OPTION)
        {
            //Récupération de la video
            this.cheminBA = fileChooser.getSelectedFile().getAbsolutePath();
        }
    }//GEN-LAST:event_button_baActionPerformed

    private void button_boActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_boActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Choisir une musique");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Musiques", "mp3", "wav","midi","flac");
        fileChooser.addChoosableFileFilter(filter);
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.setFileFilter(filter);
        if(fileChooser.showOpenDialog(this)==JFileChooser.APPROVE_OPTION)
        {
            //Récupération du fichier son
            this.cheminBO = fileChooser.getSelectedFile().getAbsolutePath();
        }
    }//GEN-LAST:event_button_boActionPerformed

    private void button_annulerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_button_annulerActionPerformed
    {//GEN-HEADEREND:event_button_annulerActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_button_annulerActionPerformed

    private void button_ajoutAActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_button_ajoutAActionPerformed
    {//GEN-HEADEREND:event_button_ajoutAActionPerformed
        try
        {

                Connection con=connexionUtils.getInstance().getConnexion();
                OraclePreparedStatement st=(OraclePreparedStatement) con.prepareStatement("SELECT id FROM PBDM_Acteur WHERE nom=?");
                st.setString(1, this.cb_acteurs.getSelectedItem().toString());
                OracleResultSet rs=(OracleResultSet) st.executeQuery();
                rs.next();
                this.l_acteurs.add(rs.getInt(1));
                this.cb_acteurs.removeItem(this.cb_acteurs.getSelectedItem());
        }
        catch (SQLException | ClassNotFoundException ex)
        {
            Logger.getLogger(frame_ajout_film.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_button_ajoutAActionPerformed

    private void button_ajoutRActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_button_ajoutRActionPerformed
    {//GEN-HEADEREND:event_button_ajoutRActionPerformed
        try
        {
            if(this.cb_real.getSelectedItem()!=null)
            {
                Connection con=connexionUtils.getInstance().getConnexion();
                OraclePreparedStatement st=(OraclePreparedStatement) con.prepareStatement("SELECT id FROM PBDM_Realisateur WHERE nom=?");
                st.setString(1, this.cb_real.getSelectedItem().toString());
                OracleResultSet rs=(OracleResultSet) st.executeQuery();
                rs.next();
                int idr=rs.getInt(1);
                this.idR=idr;
                this.cb_real.removeAllItems();
            }
        }
        catch (SQLException | ClassNotFoundException ex)
        {
            Logger.getLogger(frame_ajout_film.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_button_ajoutRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame_ajout_film.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame_ajout_film.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame_ajout_film.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame_ajout_film.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame_ajout_film().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_ajoutA;
    private javax.swing.JButton button_ajoutR;
    private javax.swing.JButton button_annuler;
    private javax.swing.JButton button_ba;
    private javax.swing.JButton button_bo;
    private javax.swing.JButton button_image;
    private javax.swing.JButton button_valider;
    private javax.swing.JComboBox<String> cb_acteurs;
    private javax.swing.JComboBox<String> cb_real;
    private javax.swing.JTextArea edition_synopsis;
    private javax.swing.JTextField field_date;
    private javax.swing.JTextField field_genre;
    private javax.swing.JTextField field_titre;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel label_date;
    private javax.swing.JLabel label_frame;
    private javax.swing.JLabel label_genre;
    private javax.swing.JLabel label_synopsis;
    private javax.swing.JLabel label_titre;
    private javax.swing.JPanel pan_buttons;
    private javax.swing.JPanel pan_image;
    private javax.swing.JPanel pan_principal;
    private javax.swing.JScrollPane pan_text;
    // End of variables declaration//GEN-END:variables
}
