/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetbdm;

/**
 *
 * @author Yann
 */
public class frame_menu extends javax.swing.JFrame
{
    boolean admin;

    /**
     * Creates new form frame_menu
     */
    public frame_menu(boolean admin)
    {
        initComponents();
        this.admin=admin;
        
        if(!admin){
            this.pan_principal.remove(pan_ajout);
            this.pan_principal.setLayout(new java.awt.GridLayout(1, 1));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu_button = new javax.swing.JButton();
        pan_principal = new javax.swing.JPanel();
        pan_recherche = new javax.swing.JPanel();
        film_button = new javax.swing.JButton();
        serie_button = new javax.swing.JButton();
        jeu_button = new javax.swing.JButton();
        personne_button = new javax.swing.JButton();
        pan_ajout = new javax.swing.JPanel();
        ajout_film_button = new javax.swing.JButton();
        ajout_serie_button = new javax.swing.JButton();
        ajout_jeu_button = new javax.swing.JButton();
        ajout_personne_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu_button.setText("Revenir à l'authentification");
        menu_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(menu_button, java.awt.BorderLayout.SOUTH);

        pan_principal.setLayout(new java.awt.GridLayout(1, 2));

        pan_recherche.setLayout(new java.awt.GridLayout(4, 1));

        film_button.setText("Rechercher un film");
        film_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                film_buttonActionPerformed(evt);
            }
        });
        pan_recherche.add(film_button);

        serie_button.setText("Rechercher une série");
        serie_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serie_buttonActionPerformed(evt);
            }
        });
        pan_recherche.add(serie_button);

        jeu_button.setText("Rechercher un jeu");
        jeu_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeu_buttonActionPerformed(evt);
            }
        });
        pan_recherche.add(jeu_button);

        personne_button.setText("Rechercher une personne");
        pan_recherche.add(personne_button);

        pan_principal.add(pan_recherche);

        pan_ajout.setLayout(new java.awt.GridLayout(4, 0));

        ajout_film_button.setText("Ajouter un film");
        ajout_film_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajout_film_buttonActionPerformed(evt);
            }
        });
        pan_ajout.add(ajout_film_button);

        ajout_serie_button.setText("Ajouter une série");
        ajout_serie_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajout_serie_buttonActionPerformed(evt);
            }
        });
        pan_ajout.add(ajout_serie_button);

        ajout_jeu_button.setText("Ajouter un jeu");
        ajout_jeu_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajout_jeu_buttonActionPerformed(evt);
            }
        });
        pan_ajout.add(ajout_jeu_button);

        ajout_personne_button.setText("Ajouter une personne");
        ajout_personne_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajout_personne_buttonActionPerformed(evt);
            }
        });
        pan_ajout.add(ajout_personne_button);

        pan_principal.add(pan_ajout);

        getContentPane().add(pan_principal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_buttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_menu_buttonActionPerformed
    {//GEN-HEADEREND:event_menu_buttonActionPerformed
        this.dispose();
    }//GEN-LAST:event_menu_buttonActionPerformed

    private void film_buttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_film_buttonActionPerformed
    {//GEN-HEADEREND:event_film_buttonActionPerformed
        /*
        frame_film ff=new frame_film(admin);
        ff.setVisible(true);
        */
    }//GEN-LAST:event_film_buttonActionPerformed

    private void serie_buttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_serie_buttonActionPerformed
    {//GEN-HEADEREND:event_serie_buttonActionPerformed
        /*
        frame_serie fs=new frame_serie(admin);
        fs.setVisible(true);
        */
    }//GEN-LAST:event_serie_buttonActionPerformed

    private void jeu_buttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jeu_buttonActionPerformed
    {//GEN-HEADEREND:event_jeu_buttonActionPerformed
       /* 
        frame_jeu fj=new frame_jeu(admin);
        fj.setVisible(true);
        */
    }//GEN-LAST:event_jeu_buttonActionPerformed

    private void ajout_film_buttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ajout_film_buttonActionPerformed
    {//GEN-HEADEREND:event_ajout_film_buttonActionPerformed
        frame_ajout_film faf=new frame_ajout_film();
        faf.setVisible(true);
    }//GEN-LAST:event_ajout_film_buttonActionPerformed

    private void ajout_serie_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajout_serie_buttonActionPerformed
        frame_ajout_serie fas=new frame_ajout_serie();
        fas.setVisible(true);
    }//GEN-LAST:event_ajout_serie_buttonActionPerformed

    private void ajout_jeu_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajout_jeu_buttonActionPerformed
        frame_ajout_jeu faj=new frame_ajout_jeu();
        faj.setVisible(true);
    }//GEN-LAST:event_ajout_jeu_buttonActionPerformed

    private void ajout_personne_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajout_personne_buttonActionPerformed
        frame_ajout_personne fap=new frame_ajout_personne();
        fap.setVisible(true);
    }//GEN-LAST:event_ajout_personne_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(frame_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(frame_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(frame_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(frame_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajout_film_button;
    private javax.swing.JButton ajout_jeu_button;
    private javax.swing.JButton ajout_personne_button;
    private javax.swing.JButton ajout_serie_button;
    private javax.swing.JButton film_button;
    private javax.swing.JButton jeu_button;
    private javax.swing.JButton menu_button;
    private javax.swing.JPanel pan_ajout;
    private javax.swing.JPanel pan_principal;
    private javax.swing.JPanel pan_recherche;
    private javax.swing.JButton personne_button;
    private javax.swing.JButton serie_button;
    // End of variables declaration//GEN-END:variables
}
