/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetbdm;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import oracle.jdbc.OracleResultSet;

/**
 *
 * @author yv965015
 */
public class frame_recherche extends javax.swing.JFrame
{
    boolean admin;
    String type_media;
    Connection con;
    /**
     * Creates new form frame_recherche
     * @param admin
     * @param typeM
     */
    public frame_recherche(boolean admin,String typeM)
    {
        initComponents();
        this.admin=admin;
        this.type_media=typeM;
        switch (this.type_media) {
                case "film" : this.film_chb.setSelected(true);this.film_chb.setEnabled(false);break;
                case "serie": this.serie_chb.setSelected(true);this.serie_chb.setEnabled(false);break;
                case "jeu" : this.jeuvideo_chb.setSelected(true);this.jeuvideo_chb.setEnabled(false);break;
                case "personne" : this.acteur_chb.setSelected(true);
                                  this.realisateur_chb.setSelected(true);this.acteur_chb.setSelected(true);
                                  this.acteur_chb.setEnabled(false);this.realisateur_chb.setEnabled(false);break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        groupe_button = new javax.swing.ButtonGroup();
        lab_typeM = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        annuler_button = new javax.swing.JButton();
        valider_button = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_rech_nom = new javax.swing.JTextField();
        pan_chb = new javax.swing.JPanel();
        jeuvideo_chb = new javax.swing.JCheckBox();
        film_chb = new javax.swing.JCheckBox();
        serie_chb = new javax.swing.JCheckBox();
        saison_chb = new javax.swing.JCheckBox();
        realisateur_chb = new javax.swing.JCheckBox();
        acteur_chb = new javax.swing.JCheckBox();

        lab_typeM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_typeM.setText("Recherche");
        getContentPane().add(lab_typeM, java.awt.BorderLayout.PAGE_START);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        annuler_button.setText("Annuler");
        annuler_button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                annuler_buttonActionPerformed(evt);
            }
        });
        jPanel4.add(annuler_button);

        valider_button.setText("Valider");
        valider_button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                valider_buttonActionPerformed(evt);
            }
        });
        jPanel4.add(valider_button);

        getContentPane().add(jPanel4, java.awt.BorderLayout.SOUTH);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        jPanel3.setLayout(new java.awt.GridLayout(2, 1));

        jLabel1.setText("Rechercher dans le synopsis");
        jPanel3.add(jLabel1);
        jPanel3.add(tf_rech_nom);

        jPanel1.add(jPanel3);

        pan_chb.setLayout(new java.awt.GridLayout(3, 2));

        groupe_button.add(jeuvideo_chb);
        jeuvideo_chb.setText("Jeu vidéo");
        jeuvideo_chb.setEnabled(false);
        pan_chb.add(jeuvideo_chb);

        groupe_button.add(film_chb);
        film_chb.setText("Film");
        film_chb.setEnabled(false);
        pan_chb.add(film_chb);

        groupe_button.add(serie_chb);
        serie_chb.setText("Serie");
        serie_chb.setEnabled(false);
        pan_chb.add(serie_chb);

        groupe_button.add(saison_chb);
        saison_chb.setText("Saison");
        saison_chb.setEnabled(false);
        pan_chb.add(saison_chb);

        realisateur_chb.setText("Réalisateur");
        realisateur_chb.setEnabled(false);
        pan_chb.add(realisateur_chb);

        acteur_chb.setText("Acteur");
        acteur_chb.setEnabled(false);
        pan_chb.add(acteur_chb);

        jPanel1.add(pan_chb);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valider_buttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_valider_buttonActionPerformed
    {//GEN-HEADEREND:event_valider_buttonActionPerformed
        try
        {
            ArrayList<Integer> list_id=new ArrayList();
            int index=0;
            frame_transition ft=new frame_transition(this.admin,"",new ArrayList(),new ArrayList(),"");
            List<String> l_noms=new ArrayList();
            if(this.tf_rech_nom.getText()!=null&&(!this.tf_rech_nom.getText().equals("")))
            {
                try {
                    con=connexionUtils.getInstance().getConnexion();
                    Statement st=con.createStatement();
                    OracleResultSet rs=null;
                    switch (this.type_media) {
                        case "film" :
                            rs=(OracleResultSet)st.executeQuery("SELECT nom,id FROM PBDM_Film WHERE CONTAINS(synopsis,'"+this.tf_rech_nom.getText()+"')>0");
                            while(rs.next())
                            {
                                index=rs.getInt(2);
                                list_id.add(index);
                            }
                            ft=new frame_transition(this.admin,this.type_media,list_id,null,"");
                            break;
                        case "jeu" :
                            rs=(OracleResultSet)st.executeQuery("SELECT nom,id FROM PBDM_JeuVideo WHERE CONTAINS(synopsis,'"+this.tf_rech_nom.getText()+"')>0");
                            while(rs.next())
                            {
                                index=rs.getInt(2);
                                list_id.add(index);
                            }
                            ft=new frame_transition(this.admin,this.type_media,list_id,null,"");
                            break;
                        case "serie" :
                            rs=(OracleResultSet)st.executeQuery("SELECT nom,id FROM PBDM_Serie WHERE CONTAINS(synopsis,'"+this.tf_rech_nom.getText()+"')>0");
                            while(rs.next())
                            {
                                index=rs.getInt(2);
                                list_id.add(index);
                            }
                            ft=new frame_transition(this.admin,this.type_media,list_id,null,"");
                            break;
                        case "personne" :
                            rs=(OracleResultSet)st.executeQuery("SELECT a.nom,a.id,r.nom,r.id FROM PBDM_Acteur a,PBDM_Realisateur r WHERE CONTAINS(a.nom,'"+this.tf_rech_nom.getText()+"')>0 OR CONTAINS(r.nom,'"+this.tf_rech_nom.getText()+"')>0");
                            while(rs.next())
                            {   
                                index=rs.getInt(2);
                                list_id.add(index);
                            }
                            ft=new frame_transition(this.admin,this.type_media,null,null,"");
                            break;
                    }
                    
                }
                catch (SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(frame_recherche.class.getName()).log(Level.SEVERE, null, ex);
                }     
            }
            else
            {
                try {
                    con=connexionUtils.getInstance().getConnexion();
                    Statement st=con.createStatement();
                    OracleResultSet rs=null;
                    
                    String nom="";
                    switch (this.type_media) {
                        case "film" :
                            rs=(OracleResultSet)st.executeQuery("SELECT nom,id FROM PBDM_Film");
                            while(rs.next())
                            {
                                index=rs.getInt(2);
                                list_id.add(index);
                            }
                            ft=new frame_transition(this.admin,this.type_media,list_id,null,"");
                            break;
                        case "jeu" :
                            rs=(OracleResultSet)st.executeQuery("SELECT nom,id FROM PBDM_JeuVideo");
                            while(rs.next())
                            {
                                index=rs.getInt(2);
                                list_id.add(index);
                            }
                            ft=new frame_transition(this.admin,this.type_media,list_id,null,"");
                            break;
                        case "serie" :
                            rs=(OracleResultSet)st.executeQuery("SELECT nom,id FROM PBDM_Serie");
                            while(rs.next())
                            {
                                index=rs.getInt(2);
                                list_id.add(index);
                            }
                            ft=new frame_transition(this.admin,this.type_media,list_id,null,"");
                            break;
                        case "personne" :
                                rs=(OracleResultSet)st.executeQuery("SELECT a.nom FROM PBDM_Acteur a");
                                while(rs.next())
                                {
                                    nom=rs.getString(1);
                                    l_noms.add(nom);
                                }
                                rs=(OracleResultSet)st.executeQuery("SELECT r.nom FROM PBDM_Realisateur r");
                                 while(rs.next())
                                {
                                    nom=rs.getString(1);
                                    System.out.println(nom);
                                    l_noms.add(nom);
                                }
                            ft=new frame_transition(this.admin,this.type_media,null,l_noms,"");
                            break;
                    }
                    
                }
                catch (SQLException ex) {
                    Logger.getLogger(frame_recherche.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            ft.setVisible(true);
        }
        catch (ClassNotFoundException | SQLException ex)
        {
            Logger.getLogger(frame_recherche.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_valider_buttonActionPerformed

    private void annuler_buttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_annuler_buttonActionPerformed
    {//GEN-HEADEREND:event_annuler_buttonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_annuler_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(frame_recherche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(frame_recherche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(frame_recherche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(frame_recherche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox acteur_chb;
    private javax.swing.JButton annuler_button;
    private javax.swing.JCheckBox film_chb;
    private javax.swing.ButtonGroup groupe_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JCheckBox jeuvideo_chb;
    private javax.swing.JLabel lab_typeM;
    private javax.swing.JPanel pan_chb;
    private javax.swing.JCheckBox realisateur_chb;
    private javax.swing.JCheckBox saison_chb;
    private javax.swing.JCheckBox serie_chb;
    private javax.swing.JTextField tf_rech_nom;
    private javax.swing.JButton valider_button;
    // End of variables declaration//GEN-END:variables
}
