/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetbdm;

import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import oracle.jdbc.OracleResultSet;

/**
 *
 * @author yv965015
 */
public class frame_transition extends javax.swing.JFrame
{
    String type_media;
    Connection con;
    boolean admin;
    /**
     * Creates new form frame_transition
     * @param typeM
     * @param l_id
     */
    public frame_transition(boolean admin,String typeM,List<Integer> l_id,List<String> l_noms) throws ClassNotFoundException, SQLException
    {
        this.admin=admin;
        initComponents();
        this.cb_listM.removeAllItems();
        this.lab_typeM.setText("Choisissez un(e) "+typeM); 
        con=connexionUtils.getInstance().getConnexion();
        Statement st=con.createStatement();
        this.type_media=typeM;
        OracleResultSet rs=null;
        String nom="";
        if(l_id!=null)
        {
                for(int i=0;i<l_id.size();i++)
                {
                    switch (this.type_media) {
                        case "film" :
                            rs=(OracleResultSet)st.executeQuery("SELECT nom FROM PBDM_Film WHERE id ="+l_id.get(i));
                            while(rs.next())
                            {
                                nom=rs.getString(1);
                                this.cb_listM.addItem(nom);
                            }
                            break;
                        case "jeu" : 
                            rs=(OracleResultSet)st.executeQuery("SELECT nom FROM PBDM_JeuVideo WHERE id ="+l_id.get(i));
                            while(rs.next())
                            {
                                nom=rs.getString(1);
                                this.cb_listM.addItem(nom);
                            }
                            break;
                        case "serie" : 
                            rs=(OracleResultSet)st.executeQuery("SELECT nom FROM PBDM_Serie WHERE id ="+l_id.get(i));
                            while(rs.next())
                            {
                                nom=rs.getString(1);
                                this.cb_listM.addItem(nom);
                            }
                            break;
                        case "personne" : 
                            rs=(OracleResultSet)st.executeQuery("SELECT a.nom,r.nom FROM PBDM_Acteur a,PBDM_Realisateur r WHERE id ="+l_id.get(i));
                            while(rs.next())
                            {
                                nom=rs.getString(1);
                                this.cb_listM.addItem(nom);
                            }
                            break;
                    }
                }
        }
        else
        {
            
            if(this.type_media.equals("personne"))
            {
                for(int i=0;i<l_noms.size();i++)
                {
                        rs=(OracleResultSet)st.executeQuery("SELECT a.nom,r.nom FROM PBDM_Acteur a,PBDM_Realisateur r WHERE nom ="+l_noms.get(i)+"'");
                        if(rs!=null)
                        {
                            while(rs.next())
                            {
                                nom=rs.getString(1);
                                this.cb_listM.addItem(nom);
                            }
                        }
                        else
                        {
                             rs=(OracleResultSet)st.executeQuery("SELECT a.nom,r.nom FROM PBDM_Acteur a,PBDM_Realisateur r WHERE nom ="+l_noms.get(i)+"'");
                             nom=rs.getString(2);
                                this.cb_listM.addItem(nom);
                        }
                        break;
                }
            }
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lab_typeM = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cb_listM = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        annuler_button = new javax.swing.JButton();
        aller_button = new javax.swing.JButton();

        lab_typeM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lab_typeM, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        jLabel1.setText("Liste des médias");
        jPanel1.add(jLabel1);

        jPanel1.add(cb_listM);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        annuler_button.setText("Annuler");
        annuler_button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                annuler_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(annuler_button);

        aller_button.setText("Aller au média");
        aller_button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                aller_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(aller_button);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void annuler_buttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_annuler_buttonActionPerformed
    {//GEN-HEADEREND:event_annuler_buttonActionPerformed
       this.setVisible(false);
    }//GEN-LAST:event_annuler_buttonActionPerformed

    private void aller_buttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aller_buttonActionPerformed
    {//GEN-HEADEREND:event_aller_buttonActionPerformed
        try
        {
            Statement st=con.createStatement();
            OracleResultSet rs=null;
            int index=0;
            if(this.cb_listM.getSelectedIndex()!=-1)
            {
                switch (this.type_media) {
                    case "film" :
                        rs=(OracleResultSet)st.executeQuery("SELECT id FROM PBDM_Film WHERE nom ='"+this.cb_listM.getSelectedItem()+"'");
                        while(rs.next())
                        {
                            index=rs.getInt(1);    
                            frame_film ff=new frame_film(this.admin,index);
                            ff.setVisible(true);
                        }
                        break;
                    case "jeu" : 
                        rs=(OracleResultSet)st.executeQuery("SELECT id FROM PBDM_JeuVideo WHERE nom ='"+this.cb_listM.getSelectedItem()+"'");
                        while(rs.next())
                        {
                            index=rs.getInt(1);
                            frame_jeu fj=new frame_jeu(this.admin,index);
                            fj.setVisible(true);
                        }
                        break;
                    case "serie" : 
                        rs=(OracleResultSet)st.executeQuery("SELECT id FROM PBDM_Serie WHERE nom ='"+this.cb_listM.getSelectedItem()+"'");
                        while(rs.next())
                        {
                            index=rs.getInt(1);
                            frame_serie fs=new frame_serie(this.admin,index);
                            fs.setVisible(true);
                        }
                        break;
                    case "personne" : 
                        rs=(OracleResultSet)st.executeQuery("SELECT a.id FROM PBDM_Acteur a WHERE a.nom ='"+this.cb_listM.getSelectedItem()+"'");
                        if(rs!=null)
                        {
                            while(rs.next())
                            {
                                index=rs.getInt(1);    
                                frame_personne fp=new frame_personne(this.admin, (String) this.cb_listM.getSelectedItem());
                            }
                        }
                        else
                        {
                            rs=(OracleResultSet)st.executeQuery("SELECT r.id FROM PBDM_Realisateur r WHERE r.nom ='"+this.cb_listM.getSelectedItem()+"'");
                            while(rs.next())
                            {
                                index=rs.getInt(1);    
                                frame_personne fp=new frame_personne(this.admin,(String)this.cb_listM.getSelectedItem());
                            }
                        }
                        break;
                }
            }
        }
        catch (SQLException ex)
        {
            Logger.getLogger(frame_transition.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (ClassNotFoundException ex)
        {
            Logger.getLogger(frame_transition.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (IOException ex)
        {
            Logger.getLogger(frame_transition.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_aller_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(frame_transition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(frame_transition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(frame_transition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(frame_transition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aller_button;
    private javax.swing.JButton annuler_button;
    private javax.swing.JComboBox<String> cb_listM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lab_typeM;
    // End of variables declaration//GEN-END:variables
}
