--CREATION DES TYPES
DROP TYPE PBDM_MediaVideo_Type FORCE;
DROP TYPE PBDM_Episode_Type FORCE;
DROP TYPE PBDM_Saison_Type FORCE;
DROP TYPE PBDM_Prenom_Type FORCE;
DROP TYPE PBDM_PrenomsV_Type FORCE;
DROP TYPE PBDM_Personne_Type FORCE;
DROP TYPE PBDM_Acteur_Type FORCE;
DROP TYPE PBDM_JeuVideo_Type FORCE;
DROP TYPE PBDM_Film_Type FORCE;
DROP TYPE PBDM_Episode_Type FORCE;
DROP TYPE PBDM_Serie_Type FORCE;
DROP TYPE PBDM_Episodes_Type FORCE;
DROP TYPE PBDM_SaisonRef_Type FORCE;
DROP TYPE PBDM_Saisons_Type FORCE;
DROP TYPE PBDM_FilmRef_Type FORCE;
DROP TYPE PBDM_Films_Type FORCE;
DROP TYPE PBDM_MedVidActeur_Type;
DROP TYPE PBDM_Realisateur_Type FORCE;

CREATE Type PBDM_MediaVideo_Type AS OBJECT 
(id NUMBER,dateSortie VARCHAR2(25), nom VARCHAR2(50), synopsis VARCHAR2(1000),genre VARCHAR2(50)) 
NOT FINAL;
/
CREATE TYPE PBDM_Realisateur_Type;
/
CREATE TYPE PBDM_Episode_Type;
/
CREATE TYPE PBDM_Saison_Type;
/
CREATE Type PBDM_Prenom_Type AS OBJECT(prenom VARCHAR2(25));
/
CREATE Type PBDM_PrenomsV_Type AS VARRAY(3) OF PBDM_Prenom_Type;
/
CREATE Type PBDM_Personne_Type AS OBJECT(id NUMBER,dateNaiss VARCHAR2(25),nom VARCHAR2(25), prenoms PBDM_PrenomsV_Type,photo ORDSYS.ORDImage,INSTANTIABLE FINAL MEMBER FUNCTION afficheP RETURN VARCHAR2,INSTANTIABLE NOT FINAL MEMBER FUNCTION affiche RETURN VARCHAR2 ) NOT FINAL;
/
CREATE Type PBDM_Acteur_Type UNDER PBDM_Personne_Type(taille INTEGER,MEMBER FUNCTION afficheA RETURN VARCHAR2,OVERRIDING MEMBER FUNCTION affiche RETURN VARCHAR2);
/
CREATE Type PBDM_JeuVideo_Type UNDER PBDM_MediaVideo_Type(note INTEGER,image ORDSYS.ORDIMAGE,MEMBER FUNCTION compareImage(id IN INTEGER,pond_AvgColor IN DOUBLE PRECISION, pond_colorhisto IN DOUBLE PRECISION, pond_poscol IN DOUBLE PRECISION,pond_text IN DOUBLE PRECISION) RETURN DOUBLE PRECISION);
/
CREATE Type PBDM_Film_Type UNDER PBDM_MediaVideo_Type (image ORDSYS.ORDImage,bandeA ORDSYS.ORDVideo, bandeO ORDSYS.ORDAudio,realisateur REF PBDM_Realisateur_Type,MEMBER FUNCTION compareImage(id IN INTEGER) RETURN DOUBLE PRECISION);
/
CREATE Type PBDM_Episode_Type UNDER PBDM_MediaVideo_Type (duree INTEGER, nomE VARCHAR2(25), numero INTEGER,saison REF PBDM_Saison_Type);
/
CREATE TYPE PBDM_Serie_Type;
/
CREATE TYPE PBDM_Episodes_Type AS TABLE OF PBDM_Episode_type;
/
CREATE Type PBDM_Saison_Type AS OBJECT (id NUMBER,nbE INTEGER, image ORDSYS.ORDImage,bandeA ORDSYS.ORDVideo,serie REF PBDM_Serie_Type,episodes PBDM_episodes_type,MEMBER FUNCTION compareImage(id IN INTEGER) RETURN DOUBLE PRECISION);
/
CREATE TYPE PBDM_SaisonRef_Type AS OBJECT(serieRef REF PBDM_Saison_Type);
/
CREATE TYPE PBDM_Saisons_Type AS TABLE OF PBDM_SaisonRef_Type;
/
CREATE Type PBDM_Serie_Type AS OBJECT (id NUMBER,image ORDSYS.ORDImage, bandeA ORDSYS.ORDVideo,nombreS INTEGER,saisons PBDM_Saisons_Type,MEMBER FUNCTION compareImage(id IN INTEGER) RETURN DOUBLE PRECISION);
/
CREATE Type PBDM_FilmRef_Type AS OBJECT (filmRef REF PBDM_Film_Type);
/
CREATE Type PBDM_Films_Type AS TABLE OF PBDM_FilmRef_Type;
/
CREATE Type PBDM_Realisateur_Type UNDER PBDM_Personne_Type (filmsR PBDM_Films_Type);
/
CREATE TYPE PBDM_MedVidActeur_Type AS OBJECT(ActeurMA REF PBDM_Acteur_Type,MedVidMA REF PBDM_MediaVideo_Type);
/
