CREATE INDEX PBDM_indexF ON PBDM_Film(nom) INDEXTYPE IS CTXSYS.CONTEXT;
CREATE INDEX PBDM_indexJ ON PBDM_JeuVideo(nom) INDEXTYPE IS CTXSYS.CONTEXT;
CREATE INDEX PBDM_indexS ON PBDM_Serie(nom) INDEXTYPE IS CTXSYS.CONTEXT;
CREATE INDEX PBDM_indexA ON PBDM_Acteur(nom) INDEXTYPE IS CTXSYS.CONTEXT;
CREATE INDEX PBDM_indexR ON PBDM_Realisateur(nom) INDEXTYPE IS CTXSYS.CONTEXT;
