CREATE INDEX PBDM_indexF ON PBDM_Film(nom) INDEXTYPE IS CTXSYS.CONTEXT;
CREATE INDEX PBDM_indexJ ON PBDM_JeuVideo(nom) INDEXTYPE IS CTXSYS.CONTEXT;
CREATE INDEX PBDM_indexS ON PBDM_Serie(nom) INDEXTYPE IS CTXSYS.CONTEXT;
CREATE INDEX PBDM_indexA ON PBDM_Acteur(nom) INDEXTYPE IS CTXSYS.CONTEXT;
CREATE INDEX PBDM_indexR ON PBDM_Realisateur(nom) INDEXTYPE IS CTXSYS.CONTEXT;

CREATE OR REPLACE TRIGGER trigger_PBDM_indexF_rebuild AFTER INSERT ON PBDM_Film FOR EACH ROW
BEGIN
	EXECUTE IMMEDIATE 'ALTER INDEX PBDM_indexF REBUILD';
END;
/

CREATE OR REPLACE TRIGGER trigger_PBDM_indexJ_rebuild AFTER INSERT ON PBDM_JeuVideo FOR EACH ROW
BEGIN
	EXECUTE IMMEDIATE 'ALTER INDEX PBDM__indexJ REBUILD';
END;
/

CREATE OR REPLACE TRIGGER trigger_PBDM__indexS_rebuild AFTER INSERT ON PBDM_Serie FOR EACH ROW
BEGIN
	EXECUTE IMMEDIATE 'ALTER INDEX PBDM__indexS REBUILD';
END;
/

CREATE OR REPLACE TRIGGER trigger_PBDM__indexA_rebuild AFTER INSERT ON PBDM_Acteur FOR EACH ROW
BEGIN
	EXECUTE IMMEDIATE 'ALTER INDEX PBDM__indexA REBUILD';
END;
/

CREATE OR REPLACE TRIGGER trigger_PBDM__indexR_rebuild AFTER INSERT ON PBDM_Realisateur FOR EACH ROW
BEGIN
	EXECUTE IMMEDIATE 'ALTER INDEX PBDM__indexR REBUILD';
END;
/
